# Configuration of the messaging system. For demo internal in-memory messaging is used
messaging:
  type_name: spade_llm.core.messaging.DictionaryMessageService
# Configuration of the agent state storage. For demo internal in-memory storage is used
storage:
  type_name: spade_llm.core.storage.InMemoryStorageFactory
chat_models:
  max:
    type_name: spade_llm.models.gigachat.GigaChatModelFactory
    args:
      credentials: env.GIGA_CRED
      scope: env.GIGACHAT_SCOPE
      model: GigaChat-2-Max
      verify_ssl_certs: False
tools:
  mcc_toolkit:
    type_name: spade_llm.demo.platform.contractnet.planning.MccToolFactory
    args:
      type_name: spade_llm.demo.platform.contractnet.planning.MccToolkit
# Agents to host in the system
agents:
  # Console agent which listens for commands from console and sends them to the delegate agent
  segment_assembler:
    type_name: spade_llm.demo.platform.contractnet.agents.SegmentAssemblerAgent
  mcc_expert:
    type_name: spade_llm.demo.platform.contractnet.planning.PlanningAgent
    args:
      system_prompt: |
        You are a MCC expert. You can help to find number value of mcc code for user query.
        Тебе сначала нужно получить подробное текстовое описание категории покупок по запросу пользователя, а потом по этому описанию найти MCC код.
        Use provided tools to solve user tasks.

      model: max

    tools:
      [ mcc_toolkit ]
  period_expert:
    type_name: spade_llm.demo.platform.contractnet.agents.PeriodExpertAgent
    args:
      model: max
      date: 2012-01-01
  spending_agent:
    type_name: spade_llm.demo.platform.contractnet.agents.SpendingProfileAgent
    args:
      model: max
  transaction_agent:
    type_name: spade_llm.demo.platform.contractnet.agents.TransactionsAgent
    args:
      model: max
  # Console agent which listens for commands from console and sends them to the delegate agent
  console:
    type_name: spade_llm.agents.console.ConsoleAgent
    args:
      delegate_type: segment_assembler
      prompt: Какой сегмент собрать?
  df:
    type_name: spade_llm.demo.platform.contractnet.discovery.DirectoryFacilitatorAgent
# Agents to wait for before stopping the system. The system stops when all agents from this list are stopped.
wait_for_agents: [ console ]
